name: customer-analytics-api
services:
- name: api
  source_dir: /
  github:
    repo: qhasan12/Customer_segmentations
    branch: main
  run_command: gunicorn Combined_API:app --bind 0.0.0.0:$PORT
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  health_check:
    http_path: /
  envs:
  - key: FLASK_ENV
    value: production
